export const REGISTER_ENDPOINT = '/api/v1/auth/register'
export const LOGIN_ENDPOINT = '/api/v1/auth/login'
export const UPDATE_USER_ENDPOINT = '/auth/updateUser'
export const JOBS_ENDPOINT = '/jobs'
export const STATS_ENDPOINT = '/jobs/stats'
